services:
  backend:                                                    
    image: saurabhkr952/backend:2.0.0
    container_name: backend
    ports:
    - "4000:4000"                                    # expose backend port
    environment:
      PORT: "4000"
      CORS_ORIGIN: "*"
      
      # DB env variables
      DB_NAME: "codeentra_schema"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DB_HOST: "3.110.96.89"
    restart: unless-stopped

