services:
  postgres:
    image: postgres:13-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: password
    network_mode: host
    restart: unless-stopped  
    volumes:
      - ./postgres-data:/var/lib/postgresql/data     
    # port= 5432

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: "localhost:5432/postgres?sslmode=disable"
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: password
    network_mode: host
    restart: unless-stopped

