services:
  backend:                                                    
    image: saurabhkr952/backend:2.0.0
    container_name: backend
    ports:
    - "4000:4000"                                            # expose backend port
    environment:
      PORT: "4000"
      CORS_ORIGIN: "*"
      
      # DB env variables
      DB_NAME: "codeentra_schema"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DB_HOST: "3.110.96.89"
    restart: unless-stopped
    networks:
      - caddy

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443                                                # expose this ports as well
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    networks:
      - caddy

networks:
  caddy:

volumes:
  caddy_data:
    external: true
  caddy_config:



### First create the folder caddy and then create the files Caddyfile. then run docker-compose -f <filename> up -d